_version = 0.1

[oop-ex-toy-robot-group]
activity_id = "oop-ex-toy-robot-group"

[team]
members = [
    "bevanlcpt024@student.wethinkcode.co.za",
    "misteyncpt024@student.wethinkcode.co.za",
    "pakerencpt024@student.wethinkcode.co.za"
]
